server:
    port: 2333
    address: "localhost"
lavalink:
    server:
        password: "p45530rd"
        sources:
            youtube: true
            bandcamp: true
            soundcloud: true
            twitch: true
            vimeo: true
            mixer: true
            http: true
            local: false
        bufferDurationMs: 400
        youtubePlaylistLoadLimit: 6
        youtubeSearchEnabled: true
        soundcloudSearchEnabled: true
        gc-warnings: true

metrics:
    prometheus:
        enabled: false
        endpoint: /metrics

sentry:
    dsn: ""

logging:
    file:
        max-history: 30
        max-size: 1GB
    path: ./logs/
    level:
        root: INFO
        lavalink: INFO
